[workspace]
members = ["plonky_block_proof_gen", "protocol_decoder"]
resolver = "2"

[workspace.dependencies]
ethereum-types = "0.14.1"
log = "0.4.20"
plonky2_evm = { git = "https://github.com/0xPolygonZero/plonky2.git", rev = "39a2d62d6d025631380da88aa78c2f8b929852a2", default-features = false }
serde = "1.0.166"
