[workspace]
members = ["plonky_block_proof_gen", "protocol_decoder"]
resolver = "2"

[workspace.dependencies]
ethereum-types = "0.14.1"
log = "0.4.20"
plonky2_evm = { git = "https://github.com/0xPolygonZero/plonky2.git", rev = "ae3003a9d7eec22384328079fd8b413ce7acb153" }
serde = "1.0.166"

# TODO: Remove once we update to the laest plonky2!
[patch."https://github.com/0xPolygonZero/eth_trie_utils.git"]
eth_trie_utils = { git = "https://github.com/0xPolygonZero/eth_trie_utils.git?rev=7fc3c3f54b3cec9c6fc5ffc5230910bd1cb77f76" }
