[package]
name = "proof_protocol_decoder"
authors = ["Polygon Zero <bgluth@polygon.technology>"]
version = "0.1.0"
edition = "2021"

[dependencies]
ciborium = "0.2.1"
ciborium-io = "0.2.1"
enumn = "0.1.12"
eth_trie_utils = { git = "https://github.com/0xPolygonZero/eth_trie_utils.git", rev = "e9ec4ec2aa2ae976b7c699ef40c1ffc716d87ed5" }
ethereum-types = "0.14.1"
hex = "0.4.3"
keccak-hash = "0.10.0"
plonky2_evm = { git = "https://github.com/0xPolygonZero/plonky2.git", rev = "49976ea2a98dcb6052bd6cf3a65f730e55727330" }
thiserror = "1.0.49"
rlp = "0.5.2"
rlp-derive = "0.1.0"
serde = "1.0.166"
